import React from 'react'
import Head from "next/head";
import BootstrapCarousel from "../public/Bootstrap"
const HomePage = () => {
  return (
    <div>
    <Head>
      <title>NAWARNI</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <BootstrapCarousel />
    </main>
  </div>

  )
}
  
export default HomePage

//pages/index.js

